[package]
name = "kartoffel-bot"
version = "0.1.0"
edition = "2021"

[dependencies]
kartoffel = { git = "https://github.com/Patryk27/kartoffels" }
# kartoffel = { path = "../kartoffels/backend/crates/kartoffel" }
